version: '3'
services:
  postgresql:
    image: postgres:15.4
    container_name: sysdesign-pg-15
    environment:
      POSTGRES_PASSWORD: "zaq12wsx"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "6543:5432"
    volumes:
      - "/Users/tzoght/pg-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: unless-stopped
    
  pgbouncer:
    depends_on:
      - postgresql  # Ensure PgBouncer starts after PostgreSQL
    image: bitnami/pgbouncer:1.20.1
    container_name: sysdesign-pg-bouncer-1_2
    ports:
      - "6432:6432"
    volumes:
      - "./pgbouncer:/etc/pgbouncer"
    environment:
      - "POSTGRESQL_PASSWORD=zaq12wsx"  # Make password consistent with PostgreSQL
    restart: unless-stopped
networks:
  mynet:
    driver: bridge