# conda env update --file environment.yml --prune
# conda env create --file environment.yml
name: kafka
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - kafka-python
    - confluent_kafka